import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: ["class"],
  content: [
    "./pages/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
    "./app/**/*.{ts,tsx}",
    "./src/**/*.{ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "tertiary-container": "#2b1705",
        "primary-fixed": "#d7e3fc",
        "on-secondary-fixed-variant": "#763300",
        "surface-container-low": "#f1f3ff",
        "inverse-primary": "#bbc7df",
        "on-primary-fixed": "#101c2e",
        "on-tertiary-fixed-variant": "#5c412b",
        "on-error": "#ffffff",
        "on-secondary-container": "#682c00",
        "on-secondary-fixed": "#331200",
        "on-tertiary-fixed": "#2b1705",
        "on-tertiary": "#ffffff",
        "primary-container": "#101c2e",
        "outline": "#75777d",
        "surface": "#f9f9ff",
        "primary": "#000000",
        "on-secondary": "#ffffff",
        "on-primary-container": "#79849b",
        "tertiary-fixed": "#ffdcc2",
        "primary-fixed-dim": "#bbc7df",
        "inverse-on-surface": "#ecf0ff",
        "on-surface-variant": "#45474c",
        "on-primary-fixed-variant": "#3c475b",
        "surface-container-highest": "#dee2f0",
        "surface-bright": "#f9f9ff",
        "inverse-surface": "#2b303b",
        "error": "#ba1a1a",
        "on-primary": "#ffffff",
        "on-error-container": "#93000a",
        "secondary": "#9b4500",
        "surface-dim": "#d6dae8",
        "background": "#f9f9ff",
        "surface-variant": "#dee2f0",
        "on-surface": "#171c26",
        "error-container": "#ffdad6",
        "surface-tint": "#535f74",
        "secondary-fixed-dim": "#ffb68e",
        "tertiary": "#000000",
        "surface-container": "#e9edfc",
        "tertiary-fixed-dim": "#e5bfa2",
        "outline-variant": "#c5c6cd",
        "on-tertiary-container": "#9e7d64",
        "on-background": "#171c26",
        "surface-container-lowest": "#ffffff",
        "surface-container-high": "#e4e8f6",
        "secondary-fixed": "#ffdbca",
        "secondary-container": "#fd8a42",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        "space-md": "1.5rem",
        "gutter-desktop": "2rem",
        "space-2xl": "4.5rem",
        "space-xs": "0.75rem",
        "space-xl": "3rem",
        "space-4xl": "8rem",
        "space-lg": "2rem",
        "space-2xs": "0.5rem",
        "space-3xs": "0.25rem",
        "gutter-tablet": "1.5rem",
        "grid-max-width": "1280px",
        "gutter-mobile": "1rem",
        "space-3xl": "6rem",
        "space-sm": "1rem",
      },
      fontFamily: {
        "label-sm": ["Manrope"],
        "label-md": ["Manrope"],
        "body-lg": ["Manrope"],
        "display": ["Manrope"],
        "body-sm": ["Manrope"],
        "body-md": ["Manrope"],
        "headline-lg": ["Manrope"],
        "display-mobile": ["Manrope"],
        "headline-lg-mobile": ["Manrope"],
        "headline-md": ["Manrope"],
        "headline-sm": ["Manrope"],
      },
      fontSize: {
        "label-sm": ["0.6875rem", { lineHeight: "1.2", letterSpacing: "0.1em", fontWeight: "600" }],
        "label-md": ["0.75rem", { lineHeight: "1.2", letterSpacing: "0.08em", fontWeight: "700" }],
        "body-lg": ["1.125rem", { lineHeight: "1.65", letterSpacing: "-0.005em", fontWeight: "400" }],
        "display": ["3.75rem", { lineHeight: "1.05", letterSpacing: "-0.035em", fontWeight: "800" }],
        "body-sm": ["0.875rem", { lineHeight: "1.5", letterSpacing: "0.005em", fontWeight: "400" }],
        "body-md": ["1rem", { lineHeight: "1.6", letterSpacing: "0em", fontWeight: "400" }],
        "headline-lg": ["2.5rem", { lineHeight: "1.15", letterSpacing: "-0.025em", fontWeight: "700" }],
        "display-mobile": ["2.5rem", { lineHeight: "1.1", letterSpacing: "-0.03em", fontWeight: "800" }],
        "headline-lg-mobile": ["1.875rem", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-md": ["1.75rem", { lineHeight: "1.25", letterSpacing: "-0.02em", fontWeight: "600" }],
        "headline-sm": ["1.25rem", { lineHeight: "1.35", letterSpacing: "-0.015em", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
};

export default config;
